Make ddev 1x-playwright work without jq (locally installed) _and_ on host _or_ inside ddev (with playwright)

diff --git a/commands/host/1x-playwright b/commands/host/1x-playwright
--- a/commands/host/1x-playwright
+++ b/commands/host/1x-playwright
@@ -15,95 +15,107 @@ GREEN='\033[0;32m'
 BROWN='\033[0;33m'
 NC='\033[0m' # No Color
 
+if ! command -v jq 2>&1 >/dev/null
+then
+  echo "Notice: jq command not found. Consider installing jq locally, using dockerized jq."
+  jq_command='docker run --rm -i ghcr.io/jqlang/jq:latest'
+else
+  jq_command='jq'
+fi
+
 ddev_hostname () {
-  if [! command -v jq &> /dev/null ]; then
-    echo "${$RED}jq command not found. Cannot determine host name - please adjust url/hostname."
-    echo "HOSTNAME"
-  else
-    echo `ddev status -j | jq -r '.["raw"]["hostnames"][0]'`
-  fi
+  echo `ddev status -j | $jq_command -r '.["raw"]["hostnames"][0]'`
 }
 
-case "$1" in
-  "ui")
-    host=$(ddev_hostname)
-    playwright_report_url="https://${host}:9324"
-    # Note: playwright "report server" hangs.
-    sleep 1 && open $playwright_report_url & jobs
-    ddev playwright test "${@:2} --ui-host=0.0.0.0 --ui-port=9323"
-    ;;
+ddev_is_installed=`ddev add-on list --installed -j | ${jq_command} -c '.raw[] | select(.Name | contains("playwright"))'`
+if [ -z "${ddev_is_installed}" ]; then
+  echo "Notice: Using playwright on host!"
+  cd test/playwright
+  npx playwright "${@:1}"
+else
+  echo "Note: Using playwright inside ddev container!"
+  case "$1" in
+    "ui")
+      host=$(ddev_hostname)
+      playwright_report_url="https://${host}:9324"
+      # Note: playwright "report server" hangs.
+      sleep 1 && open $playwright_report_url & jobs
+      ddev playwright test "${@:2} --ui-host=0.0.0.0 --ui-port=9323"
+      ;;
 
-  "codegen")
-    host=$(ddev_hostname)
-    kasmvnc_url="https://${host}:8444"
-    echo "Please note - if asked for authentication login is your username on the host (`whoami`) and the password is 'secret' (without the ')"
-    sleep 1 && open $kasmvnc_url & jobs
-    ddev playwright codegen "${@:2}"
-    ;;
+    "codegen")
+      host=$(ddev_hostname)
+      kasmvnc_url="https://${host}:8444"
+      echo "Please note - if asked for authentication login is your username on the host (`whoami`) and the password is 'secret' (without the ')"
+      sleep 1 && open $kasmvnc_url & jobs
+      ddev playwright codegen "${@:2}"
+      ;;
 
-  "test")
-    ddev playwright test "${@:2}"
-    echo "=== PLEASE NOTE: ==="
-    echo "If the output above suggest using 'npx playwright show-report' to show your generated reports, please run following command instead to avoid having to provide additional parameters:"
-    echo "ddev 1x-playwright show-report"
-    ;;
+    "test")
+      ddev playwright test "${@:2}"
+      echo "=== PLEASE NOTE: ==="
+      echo "If the output above suggest using 'npx playwright show-report' to show your generated reports, please run following command instead to avoid having to provide additional parameters:"
+      echo "ddev 1x-playwright show-report"
+      ;;
 
-  "show-report")
-    host=$(ddev_hostname)
-    playwright_report_url="https://${host}:9324"
-    # Note: playwright "report server" hangs.
-    sleep 1 && open $playwright_report_url & jobs
-    ddev playwright show-report --host=0.0.0.0
-    ;;
+    "show-report")
+      host=$(ddev_hostname)
+      playwright_report_url="https://${host}:9324"
+      # Note: playwright "report server" hangs.
+      sleep 1 && open $playwright_report_url & jobs
+      ddev playwright show-report --host=0.0.0.0
+      ;;
 
-  "cr")
-    host=$(ddev_hostname)
-    kasmvnc_url="https://${host}:8444"
-    # Note: playwright "ff|cr|wk" hangs.
-    sleep 1 && open $kasmvnc_url & jobs
-    echo "Please note - if asked for authentication login is your username on the host (`whoami`) and the password is 'secret' (without the ')"
-    ddev playwright "$1" "${@:2}"
-    ;;
+    "cr")
+      host=$(ddev_hostname)
+      kasmvnc_url="https://${host}:8444"
+      # Note: playwright "ff|cr|wk" hangs.
+      sleep 1 && open $kasmvnc_url & jobs
+      echo "Please note - if asked for authentication login is your username on the host (`whoami`) and the password is 'secret' (without the ')"
+      ddev playwright "$1" "${@:2}"
+      ;;
 
-  "ff")
-    host=$(ddev_hostname)
-    kasmvnc_url="https://${host}:8444"
-    # Note: playwright "ff|cr|wk" hangs.
-    sleep 1 && open $kasmvnc_url & jobs
-    echo "Please note - if asked for authentication login is your username on the host (`whoami`) and the password is 'secret' (without the ')"
-    ddev playwright "$1" "${@:2}"
-    ;;
+    "ff")
+      host=$(ddev_hostname)
+      kasmvnc_url="https://${host}:8444"
+      # Note: playwright "ff|cr|wk" hangs.
+      sleep 1 && open $kasmvnc_url & jobs
+      echo "Please note - if asked for authentication login is your username on the host (`whoami`) and the password is 'secret' (without the ')"
+      ddev playwright "$1" "${@:2}"
+      ;;
 
-  "wk")
-    host=$(ddev_hostname)
-    kasmvnc_url="https://${host}:8444"
-    # Note: playwright "ff|cr|wk" hangs.
-    sleep 1 && open $kasmvnc_url & jobs
-    echo "Please note - if asked for authentication login is your username on the host (`whoami`) and the password is 'secret' (without the ')"
-    ddev playwright "$1" "${@:2}"
-    ;;
+    "wk")
+      host=$(ddev_hostname)
+      kasmvnc_url="https://${host}:8444"
+      # Note: playwright "ff|cr|wk" hangs.
+      sleep 1 && open $kasmvnc_url & jobs
+      echo "Please note - if asked for authentication login is your username on the host (`whoami`) and the password is 'secret' (without the ')"
+      ddev playwright "$1" "${@:2}"
+      ;;
 
-  "kasmvnc")
-    host=$(ddev_hostname)
-    kasmvnc_url="https://${host}:8444"
-    echo "Please note - if asked for authentication login is your username on the host (`whoami`) and the password is 'secret' (without the ')"
-    open $kasmvnc_url
-    ;;
+    "kasmvnc")
+      host=$(ddev_hostname)
+      kasmvnc_url="https://${host}:8444"
+      echo "Please note - if asked for authentication login is your username on the host (`whoami`) and the password is 'secret' (without the ')"
+      open $kasmvnc_url
+      ;;
 
-  *)
-    echo "Please provide one of these commands (primarily convenience wrappers around the 'ddev playwright'-command)."
-    echo ""
-    echo "ddev 1x-playwright test [--help] [test or part of test name] - run one or more tests."
-    echo "ddev 1x-playwright show-report - starts the report server and opens a browser window to inspect report"
-    echo "ddev 1x-playwright codegen - starts the playwright codegen UI for test recording."
-    echo "ddev 1x-playwright ui - starts the in-built development UI for easier continuous testing."
-    echo ""
-    echo "ddev 1x-playwright cr|ff|wk [options] url - opens chrome (cr), firefox (ff) or webkit (wk) in the container and shows it via the kasmvnc connection in the browser."
-    echo "ddev 1x-playwright kasmvnc - opens the desktop in the web container via VNC (for e.g. watching headed test)."
-    echo ""
-    echo "Some commands have subcommands and all commands have options that you can explore with --help."
-    echo "Please note: some commands (codegen, ui, cr|ff|webkit, kasmvnc) open a new browser to show the 'embedded' desktop and authentication might be needed. Login is `whoami` and password is 'secret' (without leading/trailing ')"
-    echo ""
-    exit 0
-    ;;
-esac
+    *)
+      echo "Please provide one of these commands (primarily convenience wrappers around the 'ddev playwright'-command)."
+      echo ""
+      echo "ddev 1x-playwright test [--help] [test or part of test name] - run one or more tests."
+      echo "ddev 1x-playwright show-report - starts the report server and opens a browser window to inspect report"
+      echo "ddev 1x-playwright codegen - starts the playwright codegen UI for test recording."
+      echo "ddev 1x-playwright ui - starts the in-built development UI for easier continuous testing."
+      echo ""
+      echo "ddev 1x-playwright cr|ff|wk [options] url - opens chrome (cr), firefox (ff) or webkit (wk) in the container and shows it via the kasmvnc connection in the browser."
+      echo "ddev 1x-playwright kasmvnc - opens the desktop in the web container via VNC (for e.g. watching headed test)."
+      echo ""
+      echo "Some commands have subcommands and all commands have options that you can explore with --help."
+      echo "Please note: some commands (codegen, ui, cr|ff|webkit, kasmvnc) open a new browser to show the 'embedded' desktop and authentication might be needed. Login is `whoami` and password is 'secret' (without leading/trailing ')"
+      echo ""
+      exit 0
+      ;;
+  esac
+
+fi
